### ISSUE TITLE
Does not with with firewalla gold pro latest release

### ISSUE THREAD

**Issue by aberthil** [mbierman/pihole-installer-for-Firewalla#1]
Seems to install properly but can not reach the pihole, ping shows unreachable destination

**Comment by mbierman** [comment]
What do you mean it can't reach the pihole? How are you trying to access pihole? What do the pihole logs say? 

Did you go to http://172.16.0.2/admin/ ?

Did you opt to install the latest pihole or the one Firewalla recommended? 

I notice the one Firewalla has listed is getting a bit old. I just installed latest and it seems fine.

**Comment by aberthil** [comment]
Host mot reachable when you try to ping it or access it via the web. It can not be accessed from the network basically. Because of this can not access the logs too unless there is a way using ssh on the firewalla...It seems like there is no route defined in firewalla to access the pihole container instanceOn Oct 3, 2024, at 8:22 PM, Michael Bierman ***@***.***> wrote:﻿
What do you mean it can't reach the pihole? How are you trying to access pihole? What do the pihole logs say?

**Comment by aberthil** [comment]
Any clue of the issue here?

What I can see is that the route to the pihole is down 
***@***.***:~/.firewalla/run/docker/pi-hole (Firewalla) $ ip route
default via 10.1.10.1 dev eth0 metric 1 
default via 192.168.2.1 dev eth1 metric 2 
10.1.10.0/24 dev eth0 proto kernel scope link src 10.1.10.24 
10.189.177.0/24 dev wg0 proto kernel scope link src 10.189.177.1 
10.189.177.154 dev wg0 scope link metric 13 
10.189.177.173 dev wg0 scope link metric 13 
75.75.75.75 via 10.1.10.1 dev eth0 metric 1 
75.75.76.76 via 10.1.10.1 dev eth0 metric 1 
172.16.0.0/24 dev br-f2755d228a50 proto kernel scope link src 172.16.0.1 linkdown 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.1.0/24 dev br0 proto kernel scope link src 192.168.1.1 
192.168.2.0/24 dev eth1 proto kernel scope link src 192.168.2.2 
192.168.2.1 via 192.168.2.1 dev eth1 metric 2 



I can ping 172.16.0.1, but not 172.16.0.2 as the routing table has not the right information….

How can we fix that, the containers are up and running, the docker network is ok, but no routing info to get to the pihole….

**Comment by mbierman** [comment]
@aberthil It should be pingable. Please: 
1. Try go to http://172.16.0.2/admin/ ? http://172.16.0.2 will not work. 
2. Get the logs. When SSH'd to Firewalla, `sudo docker logs pihole`
3.  Try `sudo docker inspect pihole | grep "IPAddress"`
4. Try `sudo docker ps` You hould get something like
`CONTAINER ID   IMAGE                  COMMAND      CREATED          STATUS                    PORTS                            NAMES
a5fe91e7a8ab   pihole/pihole:latest   "/s6-init"   11 minutes ago   Up 11 minutes (healthy)   53/udp, 53/tcp, 80/tcp, 67/udp   pihole`
5. Then try
```
sudo docker inspect pihole
```

**Comment by aberthil** [comment]
ok will have a look at these
Thank you

**Comment by mbierman** [comment]
Assume this is resolved.
